### ISSUE TITLE
Getting release context fails with kubectl 1.13.x 

### ISSUE THREAD

**Issue by paksu** [Praqma/helmsman#367]
This line https://github.com/Praqma/helmsman/blame/master/internal/app/kube_helpers.go#L266 seems to be failing at least with `kubectl` versions 1.13:
```
helmsman -show-diff -no-ns -suppress-diff-secrets -f charts.yaml

 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v3.0.0-beta5
A Helm-Charts-as-Code tool.

2020-01-03 13:43:21 INFO: Parsed YAML [[ charts.yaml ]] successfully and found [ 0 ] apps
2020-01-03 13:43:21 INFO: Validating desired state definition...
2020-01-03 13:43:21 INFO: Setting up kubectl...
2020-01-03 13:43:22 INFO: Setting up helm...
2020-01-03 13:43:55 INFO: Validating charts...
2020-01-03 13:43:55 INFO: Preparing plan...
2020-01-03 13:43:55 INFO: Acquiring current Helm state from cluster...
2020-01-03 13:44:03 CRITICAL: panic: reflect.Value.Slice: slice index out of bounds

goroutine 1 [running]:
reflect.Value.Slice(0x15368c0, 0xc000904980, 0x97, 0x9, 0x0, 0x97, 0x0, 0x94)
	/usr/local/go/src/reflect/value.go:1627 +0x28c
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).evalArray(0xc0001cf8f0, 0xc000904a00, 0x1, 0x1, 0xc000281ec0, 0xc000904a00, 0x1, 0x1, 0x0, 0x0)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:273 +0x47c
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).walk(0xc0001cf8f0, 0xc000904a00, 0x1, 0x1, 0x19b7ae0, 0xc000281ec0, 0xc000904a00, 0x1, 0x1, 0x0, ...)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:148 +0x7c8
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).evalList(0xc0001cf8f0, 0xc0009049a0, 0x1, 0x1, 0xc000904280, 0x4432d1, 0xc0009049e0, 0x2999bf0, 0x0, 0xc0009049e0)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:202 +0xae
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).walk(0xc0001cf8f0, 0xc0009049a0, 0x1, 0x1, 0x19b7ca0, 0xc000904280, 0x0, 0x1, 0x1, 0x0, ...)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:142 +0x8da
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).FindResults(0xc0001cf8f0, 0x15c69c0, 0xc0001d41b0, 0xc0003ba480, 0xc0003ba480, 0x0, 0x0, 0x0)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:89 +0x21e
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).Execute(0xc0001cf8f0, 0x19ad220, 0xc00000c018, 0x15c69c0, 0xc0001d41b0, 0x101, 0x887f37)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:67 +0x49
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers.(*JSONPathPrinter).PrintObj(0xc000904380, 0x19b6b60, 0xc000904940, 0x19ad220, 0xc00000c018, 0xc000078b40, 0x40)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/jsonpath.go:139 +0x2d3
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers.ResourcePrinter.PrintObj-fm(0x19b6b60, 0xc000904940, 0x19ad220, 0xc00000c018, 0xc000338580, 0xc0003ba480)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/apply/apply_set_last_applied.go:139 +0x57
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers.ResourcePrinterFunc.PrintObj(0xc0009043a0, 0x19b6b60, 0xc000904940, 0x19ad220, 0xc00000c018, 0xc000338580, 0x8)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/interface.go:30 +0x4e
k8s.io/kubernetes/pkg/kubectl/cmd/get.(*GetOptions).printGeneric(0xc00015e540, 0xc000766300, 0xc0001e5c20, 0x1)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:828 +0x760
k8s.io/kubernetes/pkg/kubectl/cmd/get.(*GetOptions).Run(0xc00015e540, 0x19df020, 0xc0003cdb30, 0xc0005de000, 0xc0001e5c20, 0x1, 0x9, 0x0, 0x0)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:459 +0x14bc
k8s.io/kubernetes/pkg/kubectl/cmd/get.NewCmdGet.func1(0xc0005de000, 0xc0001e5c20, 0x1, 0x9)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:161 +0x115
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0005de000, 0xc0001e5b90, 0x9, 0x9, 0xc0005de000, 0xc0001e5b90)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2cc
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000213180, 0xc000255980, 0x12a05f200, 0xc00063bf28)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2fd
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000213180, 0x187f698, 0x297b160)
	/workspace/anago-v1.13.12-beta.0.14+a8b52209ee1722/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0xf3
```

Running the `kubectl` command that gets executed also throws the same error:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:12:15Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

kubectl get secret -l owner=helm,name=test-service -o=jsonpath='{.items[-1].metadata.labels}'
panic: reflect.Value.Slice: slice index out of bounds
```

I tested it with `kubectl` 1.14 and 1.17 and they both seemed to work but unfortunately we can't upgrade to those yet.

Looks like fetching the latest item in the list using jsonpath isn't really supported in this version of kubectl?

**Comment by paksu** [comment]
Are you planning to support for kubectl 1.13?

**Comment by sami-alajrami** [comment]
Currently Helmsman is packed with kubectl v1.14.10. 
May I ask what is preventing you from using kubectl v1.14.0?
