### ISSUE TITLE
Panic when a variable is not defined

### ISSUE THREAD

**Issue by ndegory** [Praqma/helmsman#473]
Panic when a variable is not defined:
```
2020-05-15 21:37:25 INFO: validating environment variables in REDACTED.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18bcbff]

goroutine 1 [running]:
github.com/Praqma/helmsman/internal/app.substituteVarsInYaml(0xc000112500, 0x71, 0xc00025fbb0, 0x0)
	/go/src/github.com/Praqma/helmsman/internal/app/utils.go:194 +0x30f
github.com/Praqma/helmsman/internal/app.substituteVarsInStaticFiles(0xc0003acf00)
	/go/src/github.com/Praqma/helmsman/internal/app/utils.go:152 +0x78c
github.com/Praqma/helmsman/internal/app.fromYAML(0x7ffeefbff439, 0x8, 0xc0003acf00, 0x2, 0x2, 0x1)
	/go/src/github.com/Praqma/helmsman/internal/app/utils.go:118 +0x147
github.com/Praqma/helmsman/internal/app.(*state).fromFile(0xc0003acf00, 0x7ffeefbff439, 0x8, 0x0, 0x0, 0xc0003b2c30)
	/go/src/github.com/Praqma/helmsman/internal/app/state.go:53 +0x11a
github.com/Praqma/helmsman/internal/app.(*cli).readState(0x23ff040, 0xc0003acdc0)
	/go/src/github.com/Praqma/helmsman/internal/app/cli.go:224 +0x49b
github.com/Praqma/helmsman/internal/app.Main()
	/go/src/github.com/Praqma/helmsman/internal/app/main.go:36 +0xba
main.main()
	/go/src/github.com/Praqma/helmsman/cmd/helmsman/main.go:8 +0x20
```
Helmsman 3.4.1, Darwin build

**Comment by sami-alajrami** [comment]
Hi @ndegory .. any steps to reproduce?
My only suspicion for now is this [line](https://github.com/Praqma/helmsman/blob/9866a4276529ea632064e9d11ae5edfa22942fa9/internal/app/utils.go#L366), but not sure where the nil pointer comes from.

**Comment by ndegory** [comment]
@sami-alajrami , I'm able to reproduce it by forgetting to set a variable used in the DSF or a values file. What happens is that an expected error triggers the call to the log.Critical() function, which is actually not defined for the logger struct.
I can submit a PR with a fix if you wish.

**Comment by eperdeme** [comment]
Also happens if you put wrong case now in ENV variables. Ie you set myenv=mooo, then call it as ${MyEnv} it'll "explode" as in the panic above.
