### ISSUE TITLE
SIGSEGV when updating the namespace of an existing release

### ISSUE THREAD

**Issue by ndegory** [Praqma/helmsman#496]
Changing the namespace in the DSF for a chart already deployed ends up with a segmentation violation.

helmsman v3.4.4

```
2020-06-23 22:39:47 NOTICE: -------- PLAN starts here --------------
2020-06-23 22:39:47 WARNING: Untracked release [ logs ] found and it will be deleted -- priority: -1000
[...]
2020-06-23 22:39:47 NOTICE: Release [ logs ] version [ 3.1.0 ] will be installed in [ monitoring ] namespace -- priority: -10
[...]
2020-06-23 22:39:47 NOTICE: -------- PLAN ends here --------------
2020-06-23 22:39:47 INFO: Sorting the commands in the plan based on priorities (order flags) ... 
2020-06-23 22:39:47 INFO: Executing plan... 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcc57dc]
goroutine 263 [running]:
github.com/Praqma/helmsman/internal/app.(*plan).exec.func1(0xc000026900, 0xc000035140, 0xf19959, 0x4, 0xc000109f80, 0x4, 0x4, 0xc000028e80, 0x3a, 0xfffffffffffffce0, ...)
	/go/src/github.com/Praqma/helmsman/internal/app/plan.go:119 +0x15c
created by github.com/Praqma/helmsman/internal/app.(*plan).exec
	/go/src/github.com/Praqma/helmsman/internal/app/plan.go:111 +0x4e2
```

**Comment by patrijua** [comment]
I stumbled into same error with 3.4.1, thought I did not realise what caused it. I deleted all existing releases and rerun the command to get past it.
