### ISSUE TITLE
Race condition in Namespace ResourceQuotas

### ISSUE THREAD

**Issue by Revellski** [Praqma/helmsman#588]
This is similar to https://github.com/Praqma/helmsman/issues/426 but affects ResourceQuotas. I suspect the fix would be similar to https://github.com/Praqma/helmsman/pull/429

**Steps to replicate:**
1. Define namespace quotas
```
namespaces:
  namespace-A:
    quotas:
      limits.cpu: "1"
      limits.memory: "1Gi"
      pods: 1
      requests.cpu: "1"
      requests.memory: "1Gi"
  namespace-B:
    quotas:
      limits.cpu: "1"
      limits.memory: "1Gi"
      pods: 1
      requests.cpu: "1"
      requests.memory: "1Gi"
```
2. Apply 
```
helmsman --apply --debug --verbose -f all.yaml
```
3. Consecutive apply/destroy operations will fail with the following:
```
2021-03-12 15:08:15 INFO: Setting up namespaces
2021-03-12 15:08:15 INFO: Looking for namespace [ namespace-A ]
2021-03-12 15:08:15 DEBUG: kubectl get namespace namespace-A
2021-03-12 15:08:15 INFO: Looking for namespace [ namespace-B ]
2021-03-12 15:08:15 DEBUG: kubectl get namespace namespace-B
2021-03-12 15:08:15 INFO: Namespace [ namespace-B ] exists
2021-03-12 15:08:15 INFO: Creating ResourceQuota in namespace [ namespace-B ]
2021-03-12 15:08:15 DEBUG: kubectl apply -f temp-ResourceQuota.yaml -n namespace-B
2021-03-12 15:08:15 INFO: Namespace [ namespace-A ] exists
2021-03-12 15:08:15 INFO: Labeling namespace [ namespace-A ]
2021-03-12 15:08:15 DEBUG: kubectl label --overwrite namespace/namespace-A  env=staging
2021-03-12 15:08:15 INFO: Creating ResourceQuota in namespace [ namespace-A ]
2021-03-12 15:08:15 DEBUG: kubectl apply -f temp-ResourceQuota.yaml -n namespace-A
2021-03-12 15:08:16 INFO: Cleaning up... deleting temp-ResourceQuota.yaml
2021-03-12 15:08:16 INFO: Cleaning up... deleting temp-ResourceQuota.yaml
2021-03-12 15:08:16 CRITICAL: Could not delete file: temp-ResourceQuota.yaml

```
Thanks

Ref
https://github.com/Praqma/helmsman/blob/232293302b255981cbea7d127942e1dbc36d79ec/internal/app/kube_helpers.go#L166

**Comment by luisdavim** [comment]
Thanks for reporting this, https://github.com/Praqma/helmsman/pull/589 should fix it, can you give it a try?

**Comment by Revellski** [comment]
https://github.com/Praqma/helmsman/issues/588 segfaults on attempt to set quotas. Cleaned-up `.helmsman-tmp` prior testing.

```
2021-03-13 09:42:00 INFO: Creating ResourceQuota in namespace [ namespace-A ]
2021-03-13 09:42:00 DEBUG: kubectl apply -f .helmsman-tmp/ResourceQuota-075781935.yaml -n namespace-A
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc46f98]
goroutine 67 [running]:
github.com/Praqma/helmsman/internal/app.setQuotas(0xc00050ef50, 0xf, 0xc000609810)
        /home/kyp/projects/helmsman/internal/app/kube_helpers.go:158 +0x3d8
github.com/Praqma/helmsman/internal/app.addNamespaces.func1(0xc00050ef50, 0xf, 0xc000534380, 0xc000332010)
        /home/kyp/projects/helmsman/internal/app/kube_helpers.go:31 +0x135
created by github.com/Praqma/helmsman/internal/app.addNamespaces
        /home/kyp/projects/helmsman/internal/app/kube_helpers.go:24 +0x12f

```

kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Revellski** [comment]
Looks good, @luisdavim, appreciate it! :beer:
