### ISSUE TITLE
Helmsman does not work with more than 256 deployments

### ISSUE THREAD

**Issue by ovi-hutu** [Praqma/helmsman#68]
Helmsman version: v1.3.0-rc
Helm version: v2.7.2

The problem is helmsman gives error when trying to deploy a new release when helm list already has 256 deployments.

```
VERBOSE: helm list --all --tiller-namespace kube-system
panic: runtime error: index out of range

goroutine 1 [running]:
main.buildState()
	/Users/samialajrami/Praqma/projects/Go-projects/src/Helmsman/helm_helpers.go:68 +0x9a3
main.makePlan(0x1c181a0, 0x1)
	/Users/samialajrami/Praqma/projects/Go-projects/src/Helmsman/decision_maker.go:13 +0x71
main.main()
	/Users/samialajrami/Praqma/projects/Go-projects/src/Helmsman/main.go:69 +0x2cc
```

The Solution will be to add the helm flag "--max 0" to the following file:
```
https://github.com/Praqma/helmsman/blob/d7d3aa86d2286bb861db7eeb511743c62768fdab/helm_helpers.go#L40
```

Thanks in advance.

**Comment by ovi-hutu** [comment]
https://github.com/Praqma/helmsman/blob/d7d3aa86d2286bb861db7eeb511743c62768fdab/helm_helpers.go#L40

**Comment by sami-alajrami** [comment]
thanks @ovi-hutu , setting it to `--max 0` will use the server's default which is hopefully larger than 256. 

https://docs.helm.sh/helm/#helm-list
```
By default, up to 256 items may be returned. To limit this, use the ‘–max’ flag. Setting ‘–max’ to 0 will not return all results. Rather, it will return the server’s default, which may be much higher than 256.
```
