### ISSUE TITLE
Helmsman fails due to Helm version failed with non-zero exit code 1

### ISSUE THREAD

**Issue by aaktaev** [Praqma/helmsman#830]
Helmsman=3.17.0
helm=3.12.3
kubernetes=1.27
kubectl=1.27.5

When launching command `helmsman --no-env-subst --apply -f rendered/deployment.yaml` it fails with error:

```
[2023-09-13 15:31:57] Run system command (start): "/opt/helmsman --no-env-subst --apply -f rendered/deployment.yaml"
[2023-09-13 15:31:58] 
[2023-09-13 15:31:58] _          _
[2023-09-13 15:31:58] | |        | |
[2023-09-13 15:31:58] | |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
[2023-09-13 15:31:58] | '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
[2023-09-13 15:31:58] | | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
[2023-09-13 15:31:58] |_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v3.17.0
[2023-09-13 15:31:58] A Helm-Charts-as-Code tool.
[2023-09-13 15:31:58] 
[2023-09-13 15:31:58] 2023-09-13 15:31:58 CRITICAL: While checking helm version: Checking Helm version failed with non-zero exit code 1: exit status 1
[2023-09-13 15:31:58] output:
[2023-09-13 15:31:58] --- stdout ---
[2023-09-13 15:31:58] 
[2023-09-13 15:31:58] --- stderr ---
[2023-09-13 15:31:58] github.com/docker/cli/cli/config.load
[2023-09-13 15:31:58] github.com/docker/cli@v23.0.1+incompatible/cli/config/config.go:128
[2023-09-13 15:31:58] github.com/docker/cli/cli/config.Load
[2023-09-13 15:31:58] github.com/docker/cli@v23.0.1+incompatible/cli/config/config.go:101
[2023-09-13 15:31:58] oras.land/oras-go/pkg/auth/docker.NewClientWithDockerFallback
[2023-09-13 15:31:58] oras.land/oras-go@v1.2.3/pkg/auth/docker/client.go:86
[2023-09-13 15:31:58] helm.sh/helm/v3/pkg/registry.NewClient
[2023-09-13 15:31:58] helm.sh/helm/v3/pkg/registry/client.go:83
[2023-09-13 15:31:58] main.newDefaultRegistryClient
[2023-09-13 15:31:58] helm.sh/helm/v3/cmd/helm/root.go:277
[2023-09-13 15:31:58] main.newRootCmd
[2023-09-13 15:31:58] helm.sh/helm/v3/cmd/helm/root.go:155
[2023-09-13 15:31:58] main.main
[2023-09-13 15:31:58] helm.sh/helm/v3/cmd/helm/helm.go:66
[2023-09-13 15:31:58] runtime.main
[2023-09-13 15:31:58] runtime/proc.go:250
[2023-09-13 15:31:58] runtime.goexit
[2023-09-13 15:31:58] runtime/asm_amd64.s:1598
Exception in thread background thread for pid 337:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.8/dist-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.8/dist-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /opt/helmsman --no-env-subst --apply -f rendered/deployment.yaml

  STDOUT:

 _          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v3.17.0
A Helm-Charts-as-Code tool.

2023-09-13 15:31:58 CRITICAL: While checking helm version: Checking Helm version failed with non-zero exit code 1: exit status 1
output: 
--- stdout ---

--- stderr ---
```

Command is launching inside docker container.

**Comment by aaktaev** [comment]
with helm=3.7.2 it works like a charm
